### ISSUE TITLE
Network "virbr0" doesn't exist by default

### ISSUE THREAD

**Issue by seriousm4x** [wubbl0rz/VmChamp#3]
`virbr0` interface didn't exist for me causing virsh errors. It's fairly simple to active this interface:

```bash
sudo virsh net-define /etc/libvirt/qemu/networks/default.xml
sudo virsh net-start default
```

Info: `dnsmasq` must be installed for this to successfully activate.

[Libvirt docs](https://wiki.libvirt.org/Networking.html#host-configuration-nat) say the xml is located at `/usr/share/libvirt/networks/default.xml` but mine was at `/etc/libvirt/qemu/networks/default.xml` (arch).

Maybe add it to the readme or ask the user if he wants to automatically active the bridge.

**Comment by wubbl0rz** [comment]
good suggestion. i could add a check at the start of new VMs to see if the interface is up and if not ask and start.

**Comment by wubbl0rz** [comment]
``` virsh --connect qemu:///system net-start --network default ```

should be enough to start if your user is in the libvirt group. if not sudo is needed.

**Comment by wubbl0rz** [comment]
next release will check if default bridge is present and offer to create one. 

![image](https://user-images.githubusercontent.com/30373916/230575929-26c34799-f653-4261-ab1d-1cd14a5d8dab.png)

**Comment by seriousm4x** [comment]
<img src="https://user-images.githubusercontent.com/23456686/230593456-3d281e7f-79fa-4705-a2b7-d045d012cfe8.png " width="200">
