### ISSUE TITLE
[Bug] Image downloads

### ISSUE THREAD

**Issue by Minecodes** [wubbl0rz/VmChamp#7]
When I download the Debian 9 or Fedora 36 image I get a 404 error. Also, downloading the Arch image over the official worldwide mirror is very slow (the time estimation said more than an hour).

**Comment by seriousm4x** [comment]
404 errors are already fixed in #5

Arch image downloads are sometimes slow, sometimes fast. This repo uses the official image listed in the [wiki](https://wiki.archlinux.org/title/Arch_Linux_on_a_VPS).

Do you know a faster/better hoster?

**Comment by Minecodes** [comment]
Only for specific countries and not worldwide

**Comment by wubbl0rz** [comment]
fixed
